# -*- coding: utf-8 -*-
"""Activity4_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-oFV9qIAvVgy5B6UoYxC-6a0VbGF1ydb
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title('Diabetes Data')
df = pd.read_csv('https://storage.googleapis.com/scsu-data-science/diabetes_nan.csv')

if st.checkbox('Show raw data'):
    st.subheader('Raw data')
    st.write(df)

st.markdown('---')
st.subheader('Diabetic vs Non-DDiabetic')

outcome = st.radio('Select outcome', ('Diabetic', 'Non-Diabetic'))

if outcome == 'Diabetic':
    filtered_df = df.loc[df['Outcome']=='1']
else:
    filtered_df = df.loc[df['Outcome']=='0']

fig, ax = plt.subplots()
ax.hist(filtered_df['Outcome'], bins=2, alpha=0.7, color='p'
ax.set_title(f'Histogram of Patients')
ax.set_xlabel('Outcome')
ax.set_ylabel('Frequency')

st.pyplot(fig)
